<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\ClientController;
use App\Http\Controllers\Api\DeliveryCompanyIntegrationController;
use App\Http\Controllers\Api\DeliveryCompanyOptionController;
use App\Http\Controllers\Api\FournisseurController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\PaiementController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\ProviderCommuneController;
use App\Http\Controllers\Api\ProviderStopDeskController;
use App\Http\Controllers\Api\ProviderWilayaController;
use App\Http\Controllers\Api\PurchaseEntryController;
use App\Http\Controllers\Api\ReturnEntryController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\StockAlertController;
use App\Http\Controllers\Api\StockController;
use App\Http\Controllers\Api\StockMovementController;
use App\Http\Controllers\Api\TransferController;
use App\Http\Controllers\Api\VersementController;
use App\Http\Controllers\Api\WalletController;
use App\Http\Controllers\Api\WarehouseController;
use App\Http\Controllers\Api\WarehouseOptionController;
use App\Http\Controllers\Api\WarehouseProductOptionController;
use App\Http\Controllers\Api\WilayaController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {

    Route::get('/products/{product}', [ProductController::class, 'show']);
    Route::get('/wilayas', [WilayaController::class, 'index']);
    Route::get('/wilayas/{wilaya}', [WilayaController::class, 'show']);
    Route::post('/orders', [OrderController::class, 'store']);

    Route::post('/login', [AuthController::class, 'login']);

    Route::middleware('auth:sanctum')->group(function () {
        Route::post('/logout', [AuthController::class, 'logout']);
        Route::get('/me', [AuthController::class, 'me']);
        Route::get('/products', [ProductController::class, 'index']);
        Route::post('/products', [ProductController::class, 'store']);
        Route::put('/products/{product}', [ProductController::class, 'update']);
        Route::delete('/products/{product}', [ProductController::class, 'destroy']);
        Route::get('/categories', [CategoryController::class, 'index']);
        Route::get('/clients', [ClientController::class, 'index']);
        Route::get('/clients/blacklist', [ClientController::class, 'blacklisted']);
        Route::put('/clients/{client}', [ClientController::class, 'update']);
        Route::delete('/clients/{client}', [ClientController::class, 'destroy']);
        Route::post('/clients/{client}/toggle-blacklist', [ClientController::class, 'toggleBlacklist']);
        Route::get('/wallets', [WalletController::class, 'index']);
        Route::post('/wallets', [WalletController::class, 'store']);
        Route::put('/wallets/{wallet}', [WalletController::class, 'update']);
        Route::delete('/wallets/{wallet}', [WalletController::class, 'destroy']);
        Route::post('/wallets/{wallet}/deposit', [WalletController::class, 'deposit']);
        Route::post('/wallets/{wallet}/withdraw', [WalletController::class, 'withdraw']);
        Route::get('/wallets/{wallet}/transactions', [WalletController::class, 'transactions']);
        Route::post('/wallets/transfer', [WalletController::class, 'transfer']);
        Route::get('/wallets/stats', [WalletController::class, 'stats']);
        Route::get('/versements', [VersementController::class, 'index']);
        Route::get('/versements/stats', [VersementController::class, 'stats']);
        Route::post('/versements', [VersementController::class, 'store']);
        Route::put('/versements/{versement}', [VersementController::class, 'update']);
        Route::delete('/versements/{versement}', [VersementController::class, 'destroy']);
        Route::get('/paiements', [PaiementController::class, 'index']);
        Route::post('/paiements', [PaiementController::class, 'store']);
        Route::put('/paiements/{paiement}', [PaiementController::class, 'update']);
        Route::delete('/paiements/{paiement}', [PaiementController::class, 'destroy']);
        Route::get('/warehouses', [WarehouseController::class, 'index']);
        Route::post('/warehouses', [WarehouseController::class, 'store']);
        Route::put('/warehouses/{warehouse}', [WarehouseController::class, 'update']);
        Route::delete('/warehouses/{warehouse}', [WarehouseController::class, 'destroy']);
        Route::post('/warehouses/{warehouse}/toggle-active', [WarehouseController::class, 'toggleActive']);
        Route::get('/roles', [RoleController::class, 'index']);
        Route::get('/roles/{role}', [RoleController::class, 'show']);
        Route::delete('/roles/{role}', [RoleController::class, 'destroy']);
        Route::get('/fournisseurs', [FournisseurController::class, 'index']);
        Route::post('/fournisseurs', [FournisseurController::class, 'store']);
        Route::put('/fournisseurs/{fournisseur}', [FournisseurController::class, 'update']);
        Route::delete('/fournisseurs/{fournisseur}', [FournisseurController::class, 'destroy']);
        Route::get('/purchase-entries', [PurchaseEntryController::class, 'index']);
        Route::post('/purchase-entries', [PurchaseEntryController::class, 'store']);
        Route::put('/purchase-entries/{purchaseEntry}', [PurchaseEntryController::class, 'update']);
        Route::post('/purchase-entries/{purchaseEntry}/confirm', [PurchaseEntryController::class, 'confirm']);
        Route::delete('/purchase-entries/{purchaseEntry}', [PurchaseEntryController::class, 'destroy']);
        Route::get('/purchase-entries/{purchaseEntry}/versements', [PurchaseEntryController::class, 'versements']);
        Route::post('/purchase-entries/{purchaseEntry}/versements', [PurchaseEntryController::class, 'createVersement']);
        Route::get('/return-entries', [ReturnEntryController::class, 'index']);
        Route::post('/return-entries', [ReturnEntryController::class, 'store']);
        Route::put('/return-entries/{returnEntry}', [ReturnEntryController::class, 'update']);
        Route::post('/return-entries/{returnEntry}/confirm', [ReturnEntryController::class, 'confirm']);
        Route::delete('/return-entries/{returnEntry}', [ReturnEntryController::class, 'destroy']);
        Route::get('/return-entries/{returnEntry}/versements', [ReturnEntryController::class, 'versements']);
        Route::post('/return-entries/{returnEntry}/versements', [ReturnEntryController::class, 'createVersement']);
        Route::get('/return-entries/purchase-entry-options', [ReturnEntryController::class, 'purchaseEntryOptions']);
        Route::get('/return-entries/purchase-entries/{purchaseEntry}/items', [ReturnEntryController::class, 'purchaseEntryItems']);
        Route::get('/stock', [StockController::class, 'index']);
        Route::post('/stock/{product}/adjust', [StockController::class, 'adjust']);
        Route::get('/stock-movements', [StockMovementController::class, 'index']);
        Route::get('/stock-alerts', [StockAlertController::class, 'index']);
        Route::get('/warehouse-options', [WarehouseOptionController::class, 'index']);
        Route::get('/warehouses/{warehouse}/product-options', [WarehouseProductOptionController::class, 'index']);
        Route::get('/transfers', [TransferController::class, 'index']);
        Route::post('/transfers', [TransferController::class, 'store']);
        Route::post('/transfers/{transfer}/confirm', [TransferController::class, 'confirm']);
        Route::delete('/transfers/{transfer}', [TransferController::class, 'destroy']);
        Route::get('/provider-wilayas', [ProviderWilayaController::class, 'index']);
        Route::get('/provider-communes', [ProviderCommuneController::class, 'index']);
        Route::get('/provider-stopdesks', [ProviderStopDeskController::class, 'index']);
        Route::get('/orders', [OrderController::class, 'index']);
        Route::get('/orders/generate-name', [OrderController::class, 'generateName']);
        Route::post('/orders/manual', [OrderController::class, 'storeManual']);
        Route::put('/orders/{order}', [OrderController::class, 'update']);
        Route::patch('/orders/{order}/status', [OrderController::class, 'updateStatus']);
        Route::get('/orders/{order}/status-history', [OrderController::class, 'statusHistory']);
        Route::delete('/orders/{order}', [OrderController::class, 'destroy']);
        Route::get('/delivery-companies', [DeliveryCompanyOptionController::class, 'index']);
        Route::get('/partners/integrations', [DeliveryCompanyIntegrationController::class, 'index']);
        Route::get('/partners/integrations/{companyKey}', [DeliveryCompanyIntegrationController::class, 'show']);
        Route::put('/partners/integrations/{companyKey}', [DeliveryCompanyIntegrationController::class, 'update']);
        Route::delete('/partners/integrations/{companyKey}', [DeliveryCompanyIntegrationController::class, 'destroy']);
    });
});
