<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BrandController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\ChargeController;
use App\Http\Controllers\Api\ClientController;
use App\Http\Controllers\Api\DeliveryCompanyIntegrationController;
use App\Http\Controllers\Api\DeliveryCompanyOptionController;
use App\Http\Controllers\Api\FournisseurController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\PaiementController;
use App\Http\Controllers\Api\PerformanceController;
use App\Http\Controllers\Api\PixelController;
use App\Http\Controllers\Api\ProductAnalyticsController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\ProductReviewController;
use App\Http\Controllers\Api\ProviderCommuneController;
use App\Http\Controllers\Api\ProviderDeliveryPriceController;
use App\Http\Controllers\Api\ProviderStopDeskController;
use App\Http\Controllers\Api\ProviderWilayaController;
use App\Http\Controllers\Api\PurchaseEntryController;
use App\Http\Controllers\Api\ReturnEntryController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\SiteSettingColorsThemeController;
use App\Http\Controllers\Api\SiteSettingLogoController;
use App\Http\Controllers\Api\StockAlertController;
use App\Http\Controllers\Api\StockController;
use App\Http\Controllers\Api\StockMovementController;
use App\Http\Controllers\Api\StorefrontCategoryController;
use App\Http\Controllers\Api\StorefrontHeroCategoryController;
use App\Http\Controllers\Api\StorefrontProductController;
use App\Http\Controllers\Api\StorefrontProductReviewController;
use App\Http\Controllers\Api\TagController;
use App\Http\Controllers\Api\TransferController;
use App\Http\Controllers\Api\VersementController;
use App\Http\Controllers\Api\WalletController;
use App\Http\Controllers\Api\WarehouseController;
use App\Http\Controllers\Api\WarehouseOptionController;
use App\Http\Controllers\Api\WarehouseProductOptionController;
use App\Http\Controllers\Api\WilayaAnalyticsController;
use App\Http\Controllers\Api\WilayaController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {

    Route::middleware('auth:sanctum')->group(function () {
        Route::get('/products/analytics', [ProductAnalyticsController::class, 'index']);
        Route::get('/products/analytics/stats', [ProductAnalyticsController::class, 'stats']);
        Route::get('/products/analytics/chart', [ProductAnalyticsController::class, 'chart']);
        Route::get('/wilayas/analytics', [WilayaAnalyticsController::class, 'index']);
        Route::put('/wilayas/{wilaya}', [WilayaController::class, 'update']);
        Route::get('/performance/revenue', [PerformanceController::class, 'revenue']);
    });

    Route::get('/products/{product}', [ProductController::class, 'show']);
    Route::get('/wilayas', [WilayaController::class, 'index']);
    Route::get('/wilayas/{wilaya}', [WilayaController::class, 'show']);
    Route::get('/provider-wilayas', [ProviderWilayaController::class, 'index']);
    Route::get('/provider-communes', [ProviderCommuneController::class, 'index']);
    Route::get('/provider-delivery-price/home', [ProviderDeliveryPriceController::class, 'home']);
    Route::post('/orders', [OrderController::class, 'store']);
    Route::get('/site-settings/colors-theme', [SiteSettingColorsThemeController::class, 'show']);
    Route::get('/site-settings/logo', [SiteSettingLogoController::class, 'show']);
    Route::get('/site-settings/hero-categories', [StorefrontHeroCategoryController::class, 'index']);
    Route::get('/storefront/products', [StorefrontProductController::class, 'index']);
    Route::get('/storefront/products/{product}', [StorefrontProductController::class, 'show']);
    Route::post('/storefront/products/{product}/reviews', [StorefrontProductReviewController::class, 'store']);
    Route::get('/storefront/categories', [StorefrontCategoryController::class, 'index']);
    Route::get('/pixels/active', [PixelController::class, 'active']);

    Route::post('/login', [AuthController::class, 'login']);

    Route::middleware('auth:sanctum')->group(function () {
        Route::post('/logout', [AuthController::class, 'logout']);
        Route::get('/me', [AuthController::class, 'me']);
        Route::put('/me', [AuthController::class, 'updateProfile']);
        Route::get('/products', [ProductController::class, 'index']);
        Route::post('/products', [ProductController::class, 'store']);
        Route::put('/products/{product}', [ProductController::class, 'update']);
        Route::delete('/products/{product}', [ProductController::class, 'destroy']);
        Route::get('/categories', [CategoryController::class, 'index']);
        Route::post('/categories', [CategoryController::class, 'store']);
        Route::put('/categories/{category}', [CategoryController::class, 'update']);
        Route::delete('/categories/{category}', [CategoryController::class, 'destroy']);
        Route::post('/categories/{category}/toggle-active', [CategoryController::class, 'toggleActive']);
        Route::get('/category-options', [CategoryController::class, 'options']);
        Route::get('/brands', [BrandController::class, 'index']);
        Route::post('/brands', [BrandController::class, 'store']);
        Route::put('/brands/{brand}', [BrandController::class, 'update']);
        Route::delete('/brands/{brand}', [BrandController::class, 'destroy']);
        Route::post('/brands/{brand}/toggle-active', [BrandController::class, 'toggleActive']);
        Route::get('/brand-options', [BrandController::class, 'options']);
        Route::get('/pixels', [PixelController::class, 'index']);
        Route::post('/pixels', [PixelController::class, 'store']);
        Route::put('/pixels/{pixel}', [PixelController::class, 'update']);
        Route::delete('/pixels/{pixel}', [PixelController::class, 'destroy']);
        Route::post('/pixels/{pixel}/toggle-active', [PixelController::class, 'toggleActive']);
        Route::get('/tags', [TagController::class, 'index']);
        Route::post('/tags', [TagController::class, 'store']);
        Route::put('/tags/{tag}', [TagController::class, 'update']);
        Route::delete('/tags/{tag}', [TagController::class, 'destroy']);
        Route::get('/tag-options', [TagController::class, 'options']);
        Route::get('/product-reviews', [ProductReviewController::class, 'index']);
        Route::put('/product-reviews/{productReview}', [ProductReviewController::class, 'update']);
        Route::delete('/product-reviews/{productReview}', [ProductReviewController::class, 'destroy']);
        Route::put('/site-settings/colors-theme', [SiteSettingColorsThemeController::class, 'update']);
        Route::put('/site-settings/logo', [SiteSettingLogoController::class, 'update']);
        Route::post('/site-settings/hero-categories', [StorefrontHeroCategoryController::class, 'store']);
        Route::put('/site-settings/hero-categories/{heroCategory}', [StorefrontHeroCategoryController::class, 'update']);
        Route::delete('/site-settings/hero-categories/{heroCategory}', [StorefrontHeroCategoryController::class, 'destroy']);
        Route::get('/clients', [ClientController::class, 'index']);
        Route::get('/clients/blacklist', [ClientController::class, 'blacklisted']);
        Route::put('/clients/{client}', [ClientController::class, 'update']);
        Route::delete('/clients/{client}', [ClientController::class, 'destroy']);
        Route::post('/clients/{client}/toggle-blacklist', [ClientController::class, 'toggleBlacklist']);
        Route::get('/wallets', [WalletController::class, 'index']);
        Route::post('/wallets', [WalletController::class, 'store']);
        Route::put('/wallets/{wallet}', [WalletController::class, 'update']);
        Route::delete('/wallets/{wallet}', [WalletController::class, 'destroy']);
        Route::post('/wallets/{wallet}/deposit', [WalletController::class, 'deposit']);
        Route::post('/wallets/{wallet}/withdraw', [WalletController::class, 'withdraw']);
        Route::get('/wallets/{wallet}/transactions', [WalletController::class, 'transactions']);
        Route::post('/wallets/transfer', [WalletController::class, 'transfer']);
        Route::get('/wallets/stats', [WalletController::class, 'stats']);
        Route::get('/versements', [VersementController::class, 'index']);
        Route::get('/versements/stats', [VersementController::class, 'stats']);
        Route::post('/versements', [VersementController::class, 'store']);
        Route::put('/versements/{versement}', [VersementController::class, 'update']);
        Route::delete('/versements/{versement}', [VersementController::class, 'destroy']);
        Route::get('/charges', [ChargeController::class, 'index']);
        Route::get('/charges/stats', [ChargeController::class, 'stats']);
        Route::post('/charges', [ChargeController::class, 'store']);
        Route::put('/charges/{charge}', [ChargeController::class, 'update']);
        Route::delete('/charges/{charge}', [ChargeController::class, 'destroy']);
        Route::get('/charges/{charge}/versements', [ChargeController::class, 'versements']);
        Route::post('/charges/{charge}/versements', [ChargeController::class, 'createVersement']);
        Route::get('/paiements', [PaiementController::class, 'index']);
        Route::post('/paiements', [PaiementController::class, 'store']);
        Route::put('/paiements/{paiement}', [PaiementController::class, 'update']);
        Route::delete('/paiements/{paiement}', [PaiementController::class, 'destroy']);
        Route::get('/warehouses', [WarehouseController::class, 'index']);
        Route::post('/warehouses', [WarehouseController::class, 'store']);
        Route::put('/warehouses/{warehouse}', [WarehouseController::class, 'update']);
        Route::delete('/warehouses/{warehouse}', [WarehouseController::class, 'destroy']);
        Route::post('/warehouses/{warehouse}/toggle-active', [WarehouseController::class, 'toggleActive']);
        Route::get('/roles', [RoleController::class, 'index']);
        Route::post('/roles', [RoleController::class, 'store']);
        Route::get('/roles/permissions', [RoleController::class, 'permissions']);
        Route::get('/roles/{role}', [RoleController::class, 'show']);
        Route::put('/roles/{role}', [RoleController::class, 'update']);
        Route::delete('/roles/{role}', [RoleController::class, 'destroy']);
        Route::get('/fournisseurs', [FournisseurController::class, 'index']);
        Route::post('/fournisseurs', [FournisseurController::class, 'store']);
        Route::put('/fournisseurs/{fournisseur}', [FournisseurController::class, 'update']);
        Route::delete('/fournisseurs/{fournisseur}', [FournisseurController::class, 'destroy']);
        Route::get('/purchase-entries', [PurchaseEntryController::class, 'index']);
        Route::post('/purchase-entries', [PurchaseEntryController::class, 'store']);
        Route::put('/purchase-entries/{purchaseEntry}', [PurchaseEntryController::class, 'update']);
        Route::post('/purchase-entries/{purchaseEntry}/confirm', [PurchaseEntryController::class, 'confirm']);
        Route::delete('/purchase-entries/{purchaseEntry}', [PurchaseEntryController::class, 'destroy']);
        Route::get('/purchase-entries/{purchaseEntry}/versements', [PurchaseEntryController::class, 'versements']);
        Route::post('/purchase-entries/{purchaseEntry}/versements', [PurchaseEntryController::class, 'createVersement']);
        Route::get('/return-entries', [ReturnEntryController::class, 'index']);
        Route::post('/return-entries', [ReturnEntryController::class, 'store']);
        Route::put('/return-entries/{returnEntry}', [ReturnEntryController::class, 'update']);
        Route::post('/return-entries/{returnEntry}/confirm', [ReturnEntryController::class, 'confirm']);
        Route::delete('/return-entries/{returnEntry}', [ReturnEntryController::class, 'destroy']);
        Route::get('/return-entries/{returnEntry}/versements', [ReturnEntryController::class, 'versements']);
        Route::post('/return-entries/{returnEntry}/versements', [ReturnEntryController::class, 'createVersement']);
        Route::get('/return-entries/purchase-entry-options', [ReturnEntryController::class, 'purchaseEntryOptions']);
        Route::get('/return-entries/purchase-entries/{purchaseEntry}/items', [ReturnEntryController::class, 'purchaseEntryItems']);
        Route::get('/stock', [StockController::class, 'index']);
        Route::get('/stock/stats', [StockController::class, 'stats']);
        Route::post('/stock/{product}/adjust', [StockController::class, 'adjust']);
        Route::get('/stock-movements', [StockMovementController::class, 'index']);
        Route::get('/stock-alerts', [StockAlertController::class, 'index']);
        Route::get('/warehouse-options', [WarehouseOptionController::class, 'index']);
        Route::get('/warehouses/{warehouse}/product-options', [WarehouseProductOptionController::class, 'index']);
        Route::get('/transfers', [TransferController::class, 'index']);
        Route::post('/transfers', [TransferController::class, 'store']);
        Route::post('/transfers/{transfer}/confirm', [TransferController::class, 'confirm']);
        Route::delete('/transfers/{transfer}', [TransferController::class, 'destroy']);
        Route::get('/provider-stopdesks', [ProviderStopDeskController::class, 'index']);
        Route::get('/orders', [OrderController::class, 'index']);
        Route::get('/orders/generate-name', [OrderController::class, 'generateName']);
        Route::post('/orders/manual', [OrderController::class, 'storeManual']);
        Route::put('/orders/{order}', [OrderController::class, 'update']);
        Route::patch('/orders/{order}/status', [OrderController::class, 'updateStatus']);
        Route::get('/orders/{order}/status-history', [OrderController::class, 'statusHistory']);
        Route::delete('/orders/{order}', [OrderController::class, 'destroy']);
        Route::get('/delivery-companies', [DeliveryCompanyOptionController::class, 'index']);
        Route::get('/partners/integrations', [DeliveryCompanyIntegrationController::class, 'index']);
        Route::get('/partners/integrations/{companyKey}', [DeliveryCompanyIntegrationController::class, 'show']);
        Route::put('/partners/integrations/{companyKey}', [DeliveryCompanyIntegrationController::class, 'update']);
        Route::delete('/partners/integrations/{companyKey}', [DeliveryCompanyIntegrationController::class, 'destroy']);
    });
});
